version: 2

run:
  timeout: 5m

linters:
  enable:
    # Focus on formatting and basic issues
    - misspell      # Fix typos
    - unconvert     # Remove unnecessary type conversions

linters-settings:
  govet:
    check-shadowing: true

  lll:
    line-length: 140

issues:
  # Be more lenient with test files
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
