repos:
  # General code quality hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Go formatting and linting
  - repo: local
    hooks:
      - id: go-fmt-workspace
        name: go fmt (per module)
        entry: bash -c 'for dir in editor git keychain lint review; do echo "Formatting $dir..."; (cd $dir && go fmt ./...) || exit 1; done; for dir in keychain/lib lint/lib; do echo "Formatting $dir..."; (cd $dir && go fmt ./...) || exit 1; done'
        language: system
        files: \.go$
        pass_filenames: false
      - id: golangci-lint-workspace
        name: golangci-lint (per module)
        entry: bash -c 'for dir in editor git keychain lint review; do echo "Linting $dir..."; (cd $dir && golangci-lint run --config=../.golangci.yml --timeout=5m) || exit 1; done; for dir in keychain/lib lint/lib; do echo "Linting $dir..."; (cd $dir && golangci-lint run --config=../../.golangci.yml --timeout=5m) || exit 1; done'
        language: system
        files: \.go$
        pass_filenames: false
