repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-added-large-files # by default, no file > 500kb should be added
  - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems
  - id: check-executables-have-shebangs # Checks that non-binary executables have a proper shebang.
  - id: check-merge-conflict # Check for files that contain merge conflict strings.
  - id: check-symlinks # Checks for symlinks which do not point to anything.
  - id: check-vcs-permalinks # Ensures that links to vcs websites are permalinks.
  - id: detect-private-key # Detects the presence of private keys
  - id: end-of-file-fixer # Makes sure files end in a newline and only a newline.
  - id: trailing-whitespace # Trims trailing whitespace.
